Concentration  トランプ52枚表示
kazuki-0914/concentration pull request #1
Opened 2020-08-31 22:02 UTC by kazuki-0914

# タスク 20200827
・pages/index.vueを画面サイズピッタリのDiv一個に変えて緑にする
・トランプ画像をassets/imagesに展開
・スクロールしなくて済む範囲内にトランプ52枚を緑のDivの中にImage52個で描画する

# 追加
ESlintの設定

2020-09-01 00:57 UTC, solufa requested changes
要修正

2020-09-01 00:57 UTC, solufa commented on components/Logo.vue
> +  >
Logo使わないからファイルごと消していいかも

2020-09-01 00:57 UTC, solufa commented on pages/index.vue
> +      <img :src="require('@/assets/png/' + filename + '.png')" class="trump" />
ES6からは加算と区別するために文字列の結合に＋を使わなくなりました
\`@/assets/png/${filename}.png`

2020-09-01 00:57 UTC, solufa commented on pages/index.vue
> +    }
Eagleではdataを使っていません
全てクラスプロパティで表現する

2020-09-01 00:57 UTC, solufa commented on pages/index.vue
> +  filenamesArray: any
原則的にanyを使ってはいけない
Arrayの場合の初期値の指定方法をEagleから推測する

2020-09-01 00:57 UTC, solufa commented on pages/index.vue
> +    }
forを使わずArray.prototype.mapを使って表現する

2020-09-01 00:57 UTC, solufa commented on pages/index.vue
> +    }
forを使わずforEachで

2020-09-01 00:57 UTC, solufa commented on pages/index.vue
>  <style>
CSSのコンフリクトを避けるため\<style scoped>

2020-09-13 16:34 UTC, kazuki-0914 commented on components/Logo.vue
> +  >
削除しました。

2020-09-13 16:44 UTC, kazuki-0914 commented on pages/index.vue
> +      <img :src="require('@/assets/png/' + filename + '.png')" class="trump" />
修正しました

2020-09-13 18:31 UTC, kazuki-0914 commented on pages/index.vue
>  <style>
追加しました

2020-09-14 16:21 UTC, kazuki-0914 commented on pages/index.vue
> +    }
data削除しました

2020-09-14 16:23 UTC, kazuki-0914 commented on pages/index.vue
> +  filenamesArray: any
配列にし、初期値を指定

2020-09-14 17:06 UTC, kazuki-0914 commented on pages/index.vue
> +    }
forから、mapに修正

2020-09-15 01:45 UTC, solufa commented on pages/index.vue
> +      const filename = mark + `00${value.number}`.slice(-2)
文字列の結合に＋を使ってはいけない

2020-09-15 01:46 UTC, solufa commented on pages/index.vue
> +      return filename
式の結果を即座にReturnするだけなら20行目のようにアロー関数を使ってワンライナーにする

2020-09-15 04:20 UTC, kazuki-0914 commented on pages/index.vue
> +    }
forEachにしました。

2020-09-15 05:03 UTC, kazuki-0914 commented on pages/index.vue
> +      const filename = mark + `00${value.number}`.slice(-2)
同じくテンプレートリテラル使うよう修正

2020-09-15 08:35 UTC, kazuki-0914 commented on pages/index.vue
> +      return filename
アロー関数を使用するように修正しました

2020-09-15 09:32 UTC, solufa commented
改行に気付いたのは素晴らしい
LGTM

2020-09-15 14:23 UTC, merged